apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role #esse permissionamento é a nivel de namespace, se quiser o nivel de cluster, deve substituir por: ClusterRole
metadata:
  name: hello-read
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #esse permissionamento é a nivel de namespace, se quiser o nivel de cluster, deve substituir por: ClusterRoleBinding
metadata:
  name: hello-read-bind
subjects:
- kind: ServiceAccount
  name: hello
  namespace: prod
roleRef:
  kind: Role #esse permissionamento é a nivel de namespace, se quiser o nivel de cluster, deve substituir por: ClusterRole
  name: hello-read
  apiGroup: rbac.authorization.k8s.io/v1 