apiVersion: apps/v1
kind: Deployment
metadata:
  name: "go-hello"
  labels:
    app: go-hello
spec:
  selector:
    matchLabels:
      app: go-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: "go-hello"
    spec:
      containers:
        - name: go-hello
          image: mateuspanda/hello:3
