apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hello-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hello
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25